version: '2'
services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "../src/main/resources/database:/docker-entrypoint-initdb.d/sql"
    environment:
      DB_CONFIG: "identity_service:identity:changeme001"

  identity-service:
    image: "${APPLICATION_IMAGE}"
    build:
      context: ../
    ports:
      - "${APPLICATION_PORT}:8080"
    environment:
        DB.HOST: "${HOST_IP}"
        DB.PORT: "${POSTGRES_PORT}"
        DB.NAME: "${POSTGRES_DB_NAME}"
        DB.USERNAME: "${POSTGRES_UNAME}"
        DB.PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - postgres
    command:
      - "java"
      - "-Xdebug"
      - "-agentlib:jdwp=transport=dt_socket,address=6000,server=y,suspend=n"
      - "-server"
      - "-jar"
      - "application.jar"